### ISSUE TITLE
'Market watchers' or 'Tradebot' action error

### ISSUE THREAD

**Issue by tobby2002** [H256/gekko-quasar-ui#25]
Hello,

I am satisfied with quasar framework and ui 
but
I got an error 
when execute 'Market watchers' or 'Tradebot' action
of LIVE GEKKO MENU

as follows:
  --> GET /api/configPart/paperTrader 200 3ms 132b
  --> GET /api/strategies 200 9ms 2.13kb
  <-- GET /api/strategies
  --> GET /api/strategies 200 3ms 2.13kb
  <-- POST /api/startGekko
2019-09-14 22:30 Gekko 2019-09-14-22-30-watcher-096423572585095 started.
  --> POST /api/startGekko 200 14ms 1.23kb
  <-- POST /api/getCandles
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_DISCONNECTED]: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:788:26)
    at ChildProcess.<anonymous> (/Users/neo1/WebstormProjects/alpha/core/workers/loadCandles/parent.js:59:10)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ChildProcess.target.disconnect (internal/child_process.js:788:12)
    at ChildProcess.<anonymous> (/Users/neo1/WebstormProjects/alpha/core/workers/loadCandles/parent.js:59:10)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
disconnect
neoui-iMac:alpha neo1$ 

ps. original gekko's source
    getCandles: function() {
but gekko-quasar-ui
    getCandles: async function () {
just async is different but it is not related with error, i tested -.-

please help me... is there any other way to solve it..

thank you

**Comment by H256** [comment]
Hi @tobby2002 . Sorry to get to this with a delay of two weeks, but it has been very busy around here and I keep this repo active very sporadic in the last time. 
Sadly, I couldn't reproduce your problem (IPC error), but from your report it sounds like a problem on gekko's backend-side. My best guess is it might have something to do with you NodeJS version you're running. What version are you running - maybe I can test it with that.
